import type { Tool } from './types';

export const SAMPLE_TOOLS: Tool[] = [
  {
    id: '1',
    name: 'DeWalt 20V Cordless Drill',
    description:
      'Professional-grade cordless drill with two batteries and charger. Perfect for everyday drilling and driving tasks.',
    category: 'power-tools',
    condition: 'excellent',
    imageUrl: '',
    owner: {
      id: 'o1',
      name: 'Mike R.',
      avatarInitials: 'MR',
      distance: '0.2 mi',
      rating: 4.9,
      toolCount: 8,
    },
    available: true,
    location: 'Oak Street',
    borrowedBy: null,
    createdAt: '2024-12-01',
  },
  {
    id: '2',
    name: 'Werner 24ft Extension Ladder',
    description:
      'Fiberglass extension ladder rated for 300 lbs. Great for painting, roof access, and tree trimming.',
    category: 'safety',
    condition: 'good',
    imageUrl: '',
    owner: {
      id: 'o2',
      name: 'Sarah K.',
      avatarInitials: 'SK',
      distance: '0.4 mi',
      rating: 5.0,
      toolCount: 3,
    },
    available: true,
    location: 'Maple Avenue',
    borrowedBy: null,
    createdAt: '2024-11-15',
  },
  {
    id: '3',
    name: 'Husqvarna Chainsaw 18"',
    description:
      'Gas-powered chainsaw with 18-inch bar. Recently sharpened chain. Includes case and safety gear.',
    category: 'garden',
    condition: 'good',
    imageUrl: '',
    owner: {
      id: 'o3',
      name: 'Tom D.',
      avatarInitials: 'TD',
      distance: '0.6 mi',
      rating: 4.7,
      toolCount: 12,
    },
    available: false,
    location: 'Elm Court',
    borrowedBy: 'Alex P.',
    createdAt: '2024-10-20',
  },
  {
    id: '4',
    name: 'Makita Sliding Miter Saw',
    description:
      '10-inch dual-bevel sliding compound miter saw. Cuts up to 2x12 at 90°. Includes laser guide.',
    category: 'power-tools',
    condition: 'excellent',
    imageUrl: '',
    owner: {
      id: 'o1',
      name: 'Mike R.',
      avatarInitials: 'MR',
      distance: '0.2 mi',
      rating: 4.9,
      toolCount: 8,
    },
    available: true,
    location: 'Oak Street',
    borrowedBy: null,
    createdAt: '2024-12-05',
  },
  {
    id: '5',
    name: ' Stanley Socket Set 150pc',
    description:
      'Complete metric and SAE socket set with ratchets, extensions, and carrying case. Mechanics-grade quality.',
    category: 'hand-tools',
    condition: 'good',
    imageUrl: '',
    owner: {
      id: 'o4',
      name: 'Jenny L.',
      avatarInitials: 'JL',
      distance: '0.3 mi',
      rating: 4.8,
      toolCount: 5,
    },
    available: true,
    location: 'Pine Road',
    borrowedBy: null,
    createdAt: '2024-11-28',
  },
  {
    id: '6',
    name: 'Laser Level — Self-Leveling',
    description:
      'Bosch self-leveling cross-line laser with tripod mount. Green beam for outdoor visibility. Battery powered.',
    category: 'measuring',
    condition: 'excellent',
    imageUrl: '',
    owner: {
      id: 'o5',
      name: 'Carlos M.',
      avatarInitials: 'CM',
      distance: '0.5 mi',
      rating: 4.6,
      toolCount: 6,
    },
    available: true,
    location: 'Birch Lane',
    borrowedBy: null,
    createdAt: '2024-12-10',
  },
  {
    id: '7',
    name: 'Kreg Pocket Hole Jig Kit',
    description:
      'Complete pocket hole joinery kit with jig, clamp, drill bit, and 200 screws. Perfect for furniture projects.',
    category: 'workshop',
    condition: 'fair',
    imageUrl: '',
    owner: {
      id: 'o2',
      name: 'Sarah K.',
      avatarInitials: 'SK',
      distance: '0.4 mi',
      rating: 5.0,
      toolCount: 3,
    },
    available: true,
    location: 'Maple Avenue',
    borrowedBy: null,
    createdAt: '2024-09-15',
  },
  {
    id: '8',
    name: 'Rototiller — Honda Mini',
    description:
      'Compact garden tiller, perfect for small garden beds. 4-stroke engine, easy to start and maneuver.',
    category: 'garden',
    condition: 'worn',
    imageUrl: '',
    owner: {
      id: 'o3',
      name: 'Tom D.',
      avatarInitials: 'TD',
      distance: '0.6 mi',
      rating: 4.7,
      toolCount: 12,
    },
    available: true,
    location: 'Elm Court',
    borrowedBy: null,
    createdAt: '2024-08-01',
  },
];
