import { useState, useCallback } from 'react';
import type { RepoAnalysis } from '../lib/types';

interface ShareButtonProps {
  analysis: RepoAnalysis;
}

function buildShareText(analysis: RepoAnalysis): string {
  const { repo, score } = analysis;
  const lines = [
    `${repo} — Reliability Score: ${score.total}/100 (${score.grade})`,
    '',
    ...Object.values(score.breakdown).map(
      (m) => `${m.label}: ${m.score}/${m.max}`
    ),
    '',
    'Generated by CommitCasualty',
  ];
  return lines.join('\n');
}

export function ShareButton({ analysis }: ShareButtonProps): JSX.Element {
  const [copied, setCopied] = useState(false);

  const handleShare = useCallback(async () => {
    const text = buildShareText(analysis);

    if (navigator.share) {
      try {
        await navigator.share({ title: `${analysis.repo} reliability`, text });
        return;
      } catch {
        // User cancelled or share failed — fall back to clipboard
      }
    }

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API unavailable — do nothing
    }
  }, [analysis]);

  return (
    <button
      onClick={handleShare}
      className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 hover:text-gray-900 transition-colors focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
      aria-label={copied ? 'Score copied to clipboard' : 'Share score'}
    >
      {copied ? (
        <>
          <svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
          Copied!
        </>
      ) : (
        <>
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
          </svg>
          Share
        </>
      )}
    </button>
  );
}
